class ResultReportGenerator {
    generateIndividualPdfReport(title, renderDatas, config) {
        let docDef = {
            info: {
                title: `Report - ${title}`,
                author: "Test Sheets System",
                creator: "Test Sheets System"
            },
            styles: this.#generateStyles(),
            content: [
                { text: title, style: "header" },
                { text: "Summary", style: "centered" },
                renderDatas.map((renderData) => this.#generateTopLevelEntry(renderData, config))
            ],
            footer: (currentPage, pageCount) => {
                return this.#generateFooter(currentPage, pageCount);
            },
            header: () => {
                return this.#generateHeader();
            }
        }
        return pdfMake.createPdf(docDef);
    }

    generateOverviewPdfReport(title, compositeRenderData, config) {
        let docDef = {
            info: {
                title: `Report - ${title}`,
                author: "Test Sheets System",
                creator: "Test Sheets System"
            },
            styles: this.#generateStyles(),
            content: [
                { text: "Summary Report", style: "header" },
                { text: title, style: "centered" },
                { text: "\n\n" },
                {
                    toc: {
                        title: { text: "Included Entries:", style: "subHeader" },
                        outlines: true
                    }
                },
                ...compositeRenderData.map((compositeData) => [
                    { text: compositeData.title, style: "header", pageBreak: 'before', tocItem: true },
                    compositeData.renderData.map((renderData) => this.#generateTopLevelEntry(renderData, config))])
            ],
            footer: (currentPage, pageCount) => {
                return this.#generateFooter(currentPage, pageCount);
            },
            header: () => {
                return this.#generateHeader();
            }
        }
        return pdfMake.createPdf(docDef);
    }

    #generateStyles() {
        return {
            header: {
                fontSize: 20,
                bold: true,
                alignment: "center"
            },
            subHeader: {
                fontSize: 14,
                bold: true,
            },
            centered: {
                alignment: "center"
            },
            footerText: {
                fontSize: 8
            },
            pass: {
                color: "darkgreen",
                bold: true
            },
            fail: {
                color: "darkred",
                bold: true
            }
        }
    }

    #generateHeader() {
        return {
            stack: [
                { text: sheetContainer.label, style: "footerText" },
                { text: getSheetFromIdentifier(sheetContainer.getSheetIdentifier()).name, style: "footerText" }
            ],
            alignment: "right",
            margin: [40, 20]
        }
    }

    #generateFooter(currentPage, pageCount) {
        return {
            columns: [
                {
                    stack: [
                        { text: "Generated by https://lukeb50.github.io/TestSheets", style: 'footerText' },
                        { text: (() => { let d = new Date(); return `At ${d.toDateString()} ${padZero(d.getHours())}:${padZero(d.getMinutes())}` })(), style: 'footerText' },
                    ]
                },
                { text: `Page ${currentPage} of ${pageCount}`, alignment: 'right', style: 'footerText' }
            ],
            margin: [40, 0]
        }
    }

    #generateTopLevelEntry(renderData, config) {
        return [
            "\n",
            { text: renderData.name, style: "subHeader", tocItem: true, tocMargin: [20, 0, 0, 0], tocStyle: { italics: true, fontSize: 12 } },
            renderData.data.map((evalData) => generateEvaluationEntry(evalData))
        ];

        function generateEvaluationEntry(evaluationEntry) {
            let isPerSituationMarking = Array.isArray(evaluationEntry.individual.marking);
            return [
                { text: "\n" },
                , {
                    layout: 'lightHorizontalLines',
                    table: {
                        headerRows: 0,
                        widths: ["*", "auto"],
                        body: [
                            [{ text: evaluationEntry.label, bold: true, color: evaluationEntry.individual.result !== null ? (evaluationEntry.individual.result === true ? "darkgreen" : "darkred") : "black" },
                            generatePassFailIndicator(evaluationEntry.individual.result)],
                            ...!shouldShowEntry(evaluationEntry, isPerSituationMarking) ?
                                [[{ text: "No must sees to show", italics: true, fontSize: 10, margin: [10, 0] }, {}]] : (() => {
                                    let entries = [];
                                    ResultReportGenerator.reportProcessSortedMustSees(sheetContainer.getSheetIdentifier(), evaluationEntry.skillId, evaluationEntry.individual, config,
                                        (text, result) => {
                                            entries.push([{ text: text }, generatePassFailIndicator(result)])
                                        }, (situationName, situationNumber) => {
                                            //Add rescuer role labels
                                            if (situationNumber !== null && evaluationEntry.individual.rescuerRole[situationNumber]) {
                                                //Per-situation values
                                                situationName += ` - ${rescuerRoles[evaluationEntry.individual.rescuerRole[situationNumber]]} Rescuer`;
                                            }
                                            if (situationNumber === null && evaluationEntry.individual.rescuerRole) {
                                                //Not per-situation
                                                situationName += ` - ${rescuerRoles[evaluationEntry.individual.rescuerRole]} Rescuer`;
                                            }
                                            entries.push([{ text: situationName, bold: true, alignment: "center", margin: [0, 5] }, {}])
                                        }, (commentText) => {
                                            entries.push([[
                                                { text: "   Comments:", italics: true },
                                                {
                                                    text: commentText,
                                                    fontSize: 10
                                                }
                                            ], {}])
                                        })
                                    return entries;
                                })()
                        ]
                    }
                }
            ];
        }

        function shouldShowEntry(evaluationEntry, isPerSituationMarking) {
            let markingCount = (isPerSituationMarking ? evaluationEntry.individual.marking : [evaluationEntry.individual.marking]).reduce((acc, currentMarking) => acc += Object.keys(currentMarking).length, 0);
            let commentCount = isPerSituationMarking ? evaluationEntry.individual.commentData.reduce((acc, comment) => acc += comment.length, 0) : evaluationEntry.individual.commentData.length;

            return markingCount + commentCount > 0;//must have a comment or some marking
        }

        function generatePassFailIndicator(result) {
            const passSvg = `<svg viewBox="0 0 24 24"> <path d="M20 6L9 17l-5-5" fill="none" stroke="darkgreen" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg>`
            const failSvg = `<svg viewBox="0 0 24 24"><path d="M6 6L18 18M18 6L6 18" fill="none" stroke="darkred" stroke-width="4" stroke-linecap="round" /></svg>`
            if (result === null) {
                return {}
            }
            return {
                columns: [
                    { text: result === true ? "Pass" : "Fail", style: result === true ? "pass" : "fail", width: "auto" },
                    { svg: result === true ? passSvg : failSvg, height: 12, width: 12, margin: [0, 0, 0, 0] }
                ],
                columnGap: 4
            }
        }
    }

    //Takes a marking instance, sorts the must-sees and outputs their names by calling a provided processing function.
    //processFunction is called with 2 arguments (text, result). Text is the string representation of the must see, and result is a boolean
    //skillHeaderProcessFunction is called with 2 arguments (situationName, situationNumber).
    //           situationName is the decoded name, situationNumber is the sit count number if per situation marking, or null otherwise
    //skillCommentProcessFunction is called with 1 argument (commentText) commentText is the raw comment text for that evaluation/skill
    static reportProcessSortedMustSees(sheetId, skillId, individual, reportConfig, mustSeeProcessFunction, skillHeaderProcessFunction, skillCommentProcessFunction) {
        let toolkitSkill = toolkitData.sheets[sheetId].skills[skillId]
        let mustSeeIdOrdering = toolkitSkill.mustSees.map((mustSee) => mustSee.id);
        let situationData = individual.teamReference.situationData ?? individual.teamReference.markingReference.situationData ?? null;
        let isPerSituationMarking = Array.isArray(individual.marking);
        if (!isPerSituationMarking && situationData) {
            skillHeaderProcessFunction(situationData.map((sit) => decodeSituationName(sit)).join(", "), null);
        }
        let markingArray = isPerSituationMarking ? individual.marking : [individual.marking];
        markingArray.forEach((mustSeeEntry, i) => {
            let comment = isPerSituationMarking ? individual.commentData[i] : individual.commentData;
            let hasComment = comment !== null && comment.length > 0;
            if ((isPerSituationMarking && Object.keys(mustSeeEntry).length > 0) || hasComment) {
                skillHeaderProcessFunction(decodeSituationName(situationData[i]), i);
            }
            let sortedMustSeeEntry = Object.fromEntries(Object.entries(mustSeeEntry).sort((a, b) => calcIndex(a) - calcIndex(b)));
            function calcIndex(a) {
                return mustSeeIdOrdering.indexOf(a[0]) >= 0 ? mustSeeIdOrdering.indexOf(a[0]) : Number.MAX_SAFE_INTEGER;
            }
            for (const [mustSeeId, result] of Object.entries(sortedMustSeeEntry)) {
                //mustSeeId is either a must-see or in the course/skill/mustsee format
                let decodedMustSee = decodeSkillReference(mustSeeId);
                let mustSeeText;
                if (decodedMustSee) {//A reference string course/skill/mustsee
                    mustSeeText = `${decodedMustSee.name} - ${decodedMustSee.mustSees.find((skillMS) => skillMS.id === mustSeeId.split("/")[2]).text}`;
                } else {//The name of a must-see from this skill
                    mustSeeText = toolkitSkill.mustSees.find((skillMS) => skillMS.id === mustSeeId).text;
                }
                //Only call if settings allow
                if (!reportConfig['resultOnlyFailMS'] || (reportConfig['resultOnlyFailMS'] && result === false)) {
                    mustSeeProcessFunction(mustSeeText, result);
                }
            }
            if (hasComment && reportConfig['resultShowComments']) {
                skillCommentProcessFunction(comment);
            }
        })

        function decodeSituationName(rawSituationReference) {
            let refSplit = rawSituationReference.split("/")
            let skillReference = getListReference(refSplit[0], toolkitData.sheets[sheetId].skills[skillId]).values.find((val) => val.id === refSplit[1]);
            if (refSplit.length === 3) {
                skillReference = decodeSkillReference(skillReference.skill).subSituations.find((subSit) => subSit.id === refSplit[2]);
            }
            return skillReference?.text ?? "Error";
        }
    }
}